# Intro to SVD

**WIP**


As you can decompose the number $24 = 3*8$ or $2*12$ or $2*3*4$ you can decompose a matrix in many different ways. SVD is only one of them. 

SVD is special decomposition of matrix *A* because:

1. **SVD decomposition always exist** for any real or complex matrix.
    * Works for any matrix, square or rectangular, full rank or not. 
    * That means you have a “go‑to” tool that you don’t have to check for eigen‑conditions, diagonalizability

2. **Insightful geometric interpretation**: SVD gives a decomposition into two orthonormal “rotations” (or orthonormal bases) and a pure scaling (the singular values). 
    * The scaling matrix allows compression and noise reductions
    * The sacling matrix allows to see the directions where the map are big (store the most of informations) and small

3. **SVD** inverse it is easy to find. When the inverse do not exist you can define **pseudo inverse** matrix $A^+$

4. **SVD** is numerical stable. 

Definiton
$$
A = U \Sigma V^T
$$

* $A$: Any $m \times n$ matrix
* $U$: Orthogonal matrix, size $m \times m$. **Rotational matrix**
* $\Sigma$: Diagonal matrix with singular values, size $m \times n$. **Scaling matrix**
* $V^T$: Transpose of orthogonal matrix $V$, size $n \times n$. **Rotational matrix**

**SVD** is useful
* Compress data
* Noise reduction

**SVD and PCA and statistics**

* $X$ (nxd) is data cloud of points (samples) and the cols are features with zero mean in all dimensions $d$

* $\Sigma$ are the sampling standard deviation of each feature $\frac{\sigma_i}{\sqrt{n-1}}$
* $V$ are the direction in input space (**principal components**). $V$ rotates the input and give you new axis. Axis of maximum variance. (**Very commun confusion**)
* $U$ are the directions in the output space

Decomposing $X$ using SVD

$$
X = U\Sigma$V^t$ 
$$

The convariance matrix

$$
\frac{1}{n-1}X^tX = V\frac{\Sigma^2}{n-1}V^t 
$$


In [12]:
import numpy as np

A = np.array([[4, 2],
              [3, 1]], dtype=float)

# NOTE: Compute SVD. 
# np.linalg.svd returns only the diagonal elements
U, s, VT = np.linalg.svd(A)

print(f"The diagonal values: {s}")

# NOTE: Build Σ as a 2x2 diagonal matrix
Sigma = np.diag(s)

print(f"A {A.shape}:\n{A}")
print(f"\nU {U.shape}:\n{U}")
print(f"\nΣ {Sigma.shape}\n: {Sigma}")
print("\nV^T:\n", VT)
print(f"\nA reconstructed (U Σ V^T):\n{A_reconstructed}")

The diagonal values: [5.4649857  0.36596619]
A (2, 2):
[[4. 2.]
 [3. 1.]]

U (2, 2):
[[-0.81741556 -0.57604844]
 [-0.57604844  0.81741556]]

Σ (2, 2)
: [[5.4649857  0.        ]
 [0.         0.36596619]]

V^T:
 [[-0.9145143  -0.40455358]
 [ 0.40455358 -0.9145143 ]]

A reconstructed (U Σ V^T):
[[4. 2.]
 [3. 1.]]


The inverse and **pseudo inverse** are:

$$
A^{-1} = V \Sigma^{-1} U^T \\
A^+ = V \Sigma^+ U^T
$$


Here is an example of $\Sigma$ and $\Sigma^+$

$$
\Sigma = \begin{bmatrix}
\sigma_1 & 0 \\
0 & \sigma_2
\end{bmatrix}
$$

and 

$$
\Sigma^+ = \begin{bmatrix}
\frac{1}{\sigma_1} & 0 \\
0 & \frac{1}{\sigma_2}
\end{bmatrix}
$$

In [1]:
import numpy as np

# Example 2x2 matrix
A = np.array([[3, 1],
              [1, 3]])

# Perform SVD
U, S, VT = np.linalg.svd(A)

# Reconstruct A to verify
Sigma = np.zeros_like(A, dtype=float)
np.fill_diagonal(Sigma, S)

A_reconstructed = U @ Sigma @ VT

print("Original A:\n", A)
print("\nU:\n", U)
print("\nSigma:\n", Sigma)
print("\nV^T:\n", VT)
print("\nReconstructed A:\n", A_reconstructed)

Original A:
 [[3 1]
 [1 3]]

U:
 [[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]

Sigma:
 [[4. 0.]
 [0. 2.]]

V^T:
 [[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]

Reconstructed A:
 [[3. 1.]
 [1. 3.]]


In [5]:
# NOTE: Compute Σ^+ (pseudo-inverse of diagonal singular value matrix)
Sigma_plus = np.zeros_like(Sigma)
for i in range(len(s)):
    if s[i] > 1e-10:   # avoid division by zero
        Sigma_plus[i, i] = 1.0 / s[i]

# Compute A^+ = V Σ^+ U^T
A_plus = VT.T @ Sigma_plus @ U.T

# Reconstruct A from SVD (for verification)
A_reconstructed = U @ Sigma @ VT

print("\nΣ:\n", Sigma)
print("\nΣ⁺:\n", Sigma_plus)
print("\nA⁺ (pseudo inverse of A):\n", A_plus)

print("\nA * A⁺:\n", A @ A_plus)
print("\nA⁺ * A:\n", A_plus @ A)


Σ:
 [[5.4649857  0.        ]
 [0.         0.36596619]]

Σ⁺:
 [[0.1829831  0.        ]
 [0.         2.73249285]]

A⁺ (pseudo inverse of A):
 [[-0.5  1. ]
 [ 1.5 -2. ]]

A * A⁺:
 [[ 1.00000000e+00  0.00000000e+00]
 [-2.22044605e-16  1.00000000e+00]]

A⁺ * A:
 [[ 1.00000000e+00  1.11022302e-16]
 [-1.77635684e-15  1.00000000e+00]]


In [1]:
import numpy as np

A = np.array([[1, 2],
              [3, 4]])

U, S, VT = np.linalg.svd(A)

print("A:\n", A)
print("\nU:\n", U)
print("\nSingular values S:\n", S)
print("\nV^T:\n", VT)

A:
 [[1 2]
 [3 4]]

U:
 [[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]

Singular values S:
 [5.4649857  0.36596619]

V^T:
 [[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]
